#!/bin/bash

# in case /dev/ttyUSB0 does not exist, wait for it
while ! test -c /dev/ttyUSB0; do
  logger -s -t setpin "waiting 3 seconds for /dev/ttyUSB0"
  sleep 3
done

# check for pin and set it if necessary
wvdial pinstatus 2>&1 | grep -q '^+CPIN: READY'
if [ $? -eq 0 ]; then
  logger -s -t setpin "SIM card is ready to use :-)"
else
  logger -s -t setpin "setting PIN"
  wvdial pin 2>/dev/null
fi

echo -en "sleeping for 3 seconds ..."
sleep 3
echo " done"
exit 0
